name: story_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_image_compress: ^2.1.0
  flutter_localizations:
    sdk: flutter
  go_router: ^13.2.0
  http: ^1.2.0
  image_picker: ^1.0.7
  intl: ^0.18.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/gif/

  fonts:
    - family: SignikaNegative
      fonts:
        - asset: assets/fonts/Signika_Negative/SignikaNegative-Bold.ttf
          weight: 700
        - asset: assets/fonts/Signika_Negative/SignikaNegative-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Signika_Negative/SignikaNegative-Medium.ttf
          weight: 500
        - asset: assets/fonts/Signika_Negative/SignikaNegative-Regular.ttf
          weight: 400
        - asset: assets/fonts/Signika_Negative/SignikaNegative-Light.ttf
          weight: 300

    - family: KronaOne
      fonts:
        - asset: assets/fonts/Krona_One/KronaOne-Regular.ttf
          weight: 400
  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
