name: story_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  http: ^1.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SignikaNegative
      fonts:
        - asset: assets/fonts/Signika_Negative/SignikaNegative-Bold.ttf
          weight: 700
        - asset: assets/fonts/Signika_Negative/SignikaNegative-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Signika_Negative/SignikaNegative-Medium.ttf
          weight: 500
        - asset: assets/fonts/Signika_Negative/SignikaNegative-Regular.ttf
          weight: 400
        - asset: assets/fonts/Signika_Negative/SignikaNegative-Light.ttf
          weight: 300

    - family: KronaOne
      fonts:
        - asset: assets/fonts/Krona_One/KronaOne-Regular.ttf
          weight: 400
  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
