name: story_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_image_compress: ^2.1.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  geocoding: ^2.2.0
  go_router: ^13.2.0
  google_maps_flutter: ^2.5.3
  http: ^1.2.0
  image_picker: ^1.0.7
  intl: ^0.18.1
  json_annotation: ^4.8.1
  location: ^5.0.3
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  sliding_clipped_nav_bar: ^3.1.0+4

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  # generate: true

  assets:
    - assets/images/
    - assets/gif/

  fonts:
    - family: SignikaNegative
      fonts:
        - asset: assets/fonts/Signika_Negative/SignikaNegative-Bold.ttf
          weight: 700
        - asset: assets/fonts/Signika_Negative/SignikaNegative-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Signika_Negative/SignikaNegative-Medium.ttf
          weight: 500
        - asset: assets/fonts/Signika_Negative/SignikaNegative-Regular.ttf
          weight: 400
        - asset: assets/fonts/Signika_Negative/SignikaNegative-Light.ttf
          weight: 300

    - family: KronaOne
      fonts:
        - asset: assets/fonts/Krona_One/KronaOne-Regular.ttf
          weight: 400
  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
